[package]
name = "tsllia-synthesis"
version = "0.1.0"
authors = ["Wonhyuk Choi <wonhyuk.choi@columbia.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
